# -*- coding: utf-8 -*-
# Generated by Django 1.11.27 on 2020-02-13 17:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_product_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='slud',
            field=models.SlugField(blank=True),
        ),
    ]
