# -*- coding: utf-8 -*-
# Generated by Django 1.11.27 on 2020-02-13 17:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_product_slud'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='slud',
            new_name='slug',
        ),
    ]
